FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build-env

WORKDIR /app

# COPY HoctoberfestSG.csproj ./
COPY . ./

RUN dotnet restore

RUN dotnet publish --configuration Release --output releaseOutput --no-restore

#build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim

WORKDIR /

COPY --from=build-env /app/releaseOutput ./

ENTRYPOINT ["dotnet", "HoctoberfestSG.dll"]
