FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build-env

WORKDIR /app

# COPY NuGet.config ./
COPY HoctoberfestSG.csproj ./
COPY NuGet.config ./

RUN dotnet restore

COPY . ./

RUN dotnet publish --configuration Release --output releaseOutput --no-restore

#build runtime image
#FROM mcr.microsoft.com/dotnet/core/aspnet:3.0
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim

WORKDIR /

COPY --from=build-env /app/releaseOutput ./

#run the container as non-root user
USER 1000

ENTRYPOINT ["dotnet", "HoctoberfestSG.dll"]
